outpath:
    /groups/hachgrp/projects/dev-RNAInFuser/analysis/RI-experiments/paper

RI_experiments:
    RI_1:
        sample : 'MCF7-sgnex'
        pipeline:
            - Xpr:
                ''
            - Spc:
                '--molecule-count 1000000'
            - plA:
                '--normal=40,10 --min-length=5 --expand-isoforms'
            - PCR:
                '--cycles 5 -X Taq-setting1'
            - Trc:
                '--only-single-isoform'
            - Seq:
                '--other-br="--tail_noise_model=nanopore"'
    RI_2:
        sample : 'N1'
        pipeline:
            - Xpr_sc:
                ''
            - Spc:
                '--molecule-count 1000000'
            - plA:
                '--normal=40,10 --min-length=5 --expand-isoforms'
            - SCB:
                ''
            - UMI:
                '--format5 10'
            - PCR:
                '--cycles 5 -X Taq-setting1'
            - Trc:
                '--only-single-isoform'
            - Seq:
                '--other-br="--tail_noise_model=nanopore"'
NS_experiments:
    NS_1:
        sample : 'MCF7-sgnex'
        simulation_params:
            '-n 100000 --seed 42'

plots:
    - {
        rule: raw_lengths,
        data: [MCF7-sgnex, RI_1, NS_1],
        title: ''
    }
    - {
        rule: raw_lengths,
        data: [N1, RI_2],
        title: ''
    }
    # - {
    #     rule: mapped_raw_lengths,
    #     data: [MCF7-sgnex, 'RI_1'],
    #     title: ''
    # }
    # - {
    #     rule: mapped_lengths,
    #     data: [MCF7-sgnex, NS_1],
    #     title: ''
    # }
    # - {
    #     rule: substition,
    #     data: [MCF7-sgnex, NS_1],
    #     title: ''
    # }
    # - {
    #     rule: polyA,
    #     data: [MCF7-sgnex, NS_1],
    #     title: ''
    # }

exec:
    RI_splicer:
        build/splicer
    RI_polyA:
        build/polyA
    RI_pcr:
        build/pcr
    RI_sc_barcoder:
        build/single-cell-barcoder
    RI_umi:
        build/umi
    RI_truncate:
        build/truncate
    RI_sequencer:
        build/sequencer
    badread:
        /groups/hachgrp/projects/dev-simulation/code/Badread/badread-runner.py
    transcript_abundance:
        py/transcript_abundance.py
    truncate_kde:
        py/truncate_kde.py
    tNS_simulate:
        read_analysis.py
    tNS_analyze:
        simulator.py

refs:
    cDNA:
        data/refs/Homo_sapiens.GRCh38.cdna.all.fa
    DNA:
        data/refs/Homo_sapiens.GRCh38.dna.primary_assembly.fa
    GTF:
        data/refs/Homo_sapiens.GRCh38.108.gtf
    10x_bc:
        data/refs/3M-february-2018.txt.gz

samples:
    'MCF7-sgnex':
        fastq:
            - data/samples/MCF7-sgnex.fastq.gz
    'N1':
        fastq:
            - data/samples/N1.fastq
