outpath:
    /groups/hachgrp/projects/dev-RNAInFuser/analysis/RI-experiments/paper

RI_experiments:
    RI_1:
        sample : 'MCF7-sgnex'
        pipeline:
            - Xpr:
                ''
            - Spc:
                '--molecule-count 1000000'
            - plA:
                '--normal=40,10 --min-length=5 --expand-isoforms'
            - PCR:
                '--cycles 5 -x Taq-setting1'
            - Trc:
                '--only-single-isoform'
            - Seq:
                '--other-br="--tail_noise_model=nanopore"'
    RI_1_chr21:
        sample : 'MCF7-sgnex_chr21'
        pipeline:
            - Xpr:
                ''
            - Spc:
                '--molecule-count 5000'
            - plA:
                '--normal=40,10 --min-length=5 --expand-isoforms'
            - PCR:
                '--cycles 5 -x Taq-setting1'
            - Trc:
                '--only-single-isoform'
            - Seq:
                '--other-br="--tail_noise_model=nanopore"'
    RI_2:
        sample : 'N1_chr21'
        pipeline:
            - Xpr_sc:
                ''
            - Spc:
                '--molecule-count 1000000'
            - plA:
                '--normal=40,10 --min-length=5 --expand-isoforms'
            - SCB:
                ''
            - UMI:
                '--format5 10'
            - PCR:
                '--cycles 5 -x Taq-setting1'
            - Trc:
                '--only-single-isoform'
            - Seq:
                '--other-br="--tail_noise_model=nanopore"'
NS_experiments:
    NS_1:
        sample : 'MCF7-sgnex'
        simulation_params:
            '-n 100000 --seed 42'
    NS_1_chr21:
        sample : 'MCF7-sgnex_chr21'
        simulation_params:
            '-n 50000 --seed 42'

plots:
    - {
        rules: [raw_lengths,mapped_raw_lengths,mapped_lengths, substition],
        data: [MCF7-sgnex_chr21, RI_1_chr21, NS_1_chr21],
    }
    
exec:
    RI_splicer:
        build/splicer
    RI_polyA:
        build/polyA
    RI_pcr:
        build/pcr
    RI_sc_barcoder:
        build/single-cell-barcoder
    RI_umi:
        build/umi
    RI_truncate:
        build/truncate
    RI_sequencer:
        build/sequencer
    badread:
        /groups/hachgrp/projects/dev-simulation/code/Badread/badread-runner.py
    transcript_abundance:
        py/transcript_abundance.py
    truncate_kde:
        py/truncate_kde.py
    tNS_simulate:
        read_analysis.py
    tNS_analyze:
        simulator.py

refs:
    Homo_sapiens:
        cDNA:
            data/refs/Homo_sapiens.GRCh38.cdna.all.fa
        DNA:
            data/refs/Homo_sapiens.GRCh38.dna.primary_assembly.fa
        GTF:
            data/refs/Homo_sapiens.GRCh38.108.gtf
    Homo_sapiens_chr21:
        cDNA:
            data/refs/Homo_sapiens.GRCh38.cdna.all.fa
        DNA:
            data/refs/Homo_sapiens.GRCh38.dna.primary_assembly.fa
        GTF:
            data/refs/Homo_sapiens.GRCh38.108.gtf
    10x_bc:
        data/refs/3M-february-2018.txt.gz

samples:
    'MCF7-sgnex':
        fastq:
            - data/samples/MCF7-sgnex.fastq.gz
        ref:
            Homo_sapiens
    'MCF7-sgnex_chr21':
        fastq:
            - data/samples/MCF7-sgnex_subsample.fastq.gz
        ref:
            Homo_sapiens_chr21
    'N1':
        fastq:
            - data/samples/N1.fastq
        ref:
            Homo_sapiens
    'N1_chr21':
        fastq:
            - data/samples/N1_subsample.fastq.gz
        ref:
            Homo_sapiens_chr21
