outpath: /groups/hachgrp/projects/dev-tksm/analysis/paper

TS_experiments:
    TKSM_bulk:
        pipeline:
            - Tsb:
                params: "--molecule-count 1000000"
                model: "MCF7-sgnex"
                mode: Xpr
            - Trc:
                params: ""
                model: "MCF7-sgnex"
            - plA:
                params: "--normal=15,7.5"
            - Flp:
                params: "-p 0.5"
            - Tag:
                params: "--format5 AATGTACTTCGTTCAGTTACGTATTGCT --format3 GCAATACGTAACTGAACGAAGT"
            - Seq:
                params: "--skip-qual-compute"
                model: "MCF7-sgnex"
    single_cell_head:
        pipeline:
            - Tsb:
                params: "--molecule-count 1000000"
                model: "N1"
                mode: Xpr_sc
            - Trc:
                params: ""
                model: "N1"
    single_cell_p1:
        pipeline:
            - Mrg:
                sources: ["single_cell_head",]
            - Flt:
                params: "-c \"info CB\""
            - plA:
                params: "--normal=15,7.5"
            - Tag: 
                params: "--format3 10"
            - SCB: 
                params: ""
            - Tag:
                params: "--format3 AGATCGGAAGAGCGTCGTGTAG"
    single_cell_p2:
        pipeline:
            - Mrg:
                sources: ["single_cell_head",]
            - Flt:
                params: "-c \"info CB\" --negate"
    TKSM_single_cell:
        pipeline:
            - Mrg:
                sources: ["single_cell_p1", "single_cell_p2"]
            - PCR:
                params: "--cycles 5 --molecule-count 5000000"
            - Flp:
                params: "-p 0.5"
            - Tag:
                params: "--format5 AATGTACTTCGTTCAGTTACGTATTGCT --format3 GCAATACGTAACTGAACGAAGT"
            - Seq:
                params: "--skip-qual-compute"
                model: "N1"
    TKSM_gene_fusion:
        pipeline:
            - Tsb:
                params: "--molecule-count 1000000 --fusion-count 100"
                model: "MCF7-sgnex"
                mode: Xpr
            - Trc:
                params: ""
                model: "MCF7-sgnex"
            - plA:
                params: "--normal=15,7.5"
            - PCR:
                params: "--cycles 5 --molecule-count 5000000"
            - Flp:
                params: "-p 0.5"
            - Tag:
                params: "--format5 AATGTACTTCGTTCAGTTACGTATTGCT --format3 GCAATACGTAACTGAACGAAGT"
            - Seq:
                params: "--skip-qual-compute"
                model: "MCF7-sgnex"

NS_experiments:
    nanosim_bulk:
        sample: "MCF7-sgnex"
        simulation_params: "-n 1000000 --seed 42"

plots:
    - {
        rules: [
            raw_lengths,
            mapped_raw_lengths,
            mapped_lengths,
            substitution,
            polyA,
            tpm_plot_tksm,
            tpm_plot_tksm.by_gene,
            tpm_plot_tksm_sc.by_gene,
            tpm_plot_liqa,
            tpm_plot_minimap2,
            lr_sr_adapt,
        ],
        data: [
            N1,
            TKSM_single_cell,
        ],
      }
    - {
        rules: [
            raw_lengths,
            mapped_raw_lengths,
            mapped_lengths,
            substitution,
            polyA,
            tpm_plot_tksm,
            tpm_plot_liqa,
            tpm_plot_minimap2,
            tpm_plot_nanosim,
        ],
        data: [
            MCF7-sgnex,
            TKSM_bulk,
            nanosim_bulk,
        ],
    }
    - {
        rules: [
            raw_lengths,
            mapped_raw_lengths,
            mapped_lengths,
            substitution,
            polyA,
            tpm_plot_tksm,
            tpm_plot_liqa,
            tpm_plot_minimap2,
            tpm_plot_nanosim,
        ],
        data: [
            MCF7-sgnex,
            TKSM_gene_fusion,
        ],
    }

exec:
    tksm: build/bin/tksm
    tNS_analyze: simulator.py
    lr_cell_stats: py/lr_cell_stats.py

refs:
    Homo_sapiens:
        cDNA: data/refs/Homo_sapiens.GRCh38.cdna.chr.fa
        DNA: data/refs/Homo_sapiens.GRCh38.dna.primary_assembly.fa
        GTF: data/refs/Homo_sapiens.GRCh38.108.chr.gtf
    Homo_sapiens_chr21:
        cDNA: data/refs/Homo_sapiens.GRCh38.cdna.chr21.fa
        DNA: data/refs/Homo_sapiens.GRCh38.dna.primary_assembly.chr21.fa
        GTF: data/refs/Homo_sapiens.GRCh38.108.chr21.gtf
    10x_bc: data/refs/3M-february-2018.txt.gz

samples:
    "MCF7-sgnex":
        fastq:
            - data/samples/MCF7-sgnex.fastq.gz
        ref: Homo_sapiens
    "N1":
        fastq:
            - data/samples/N1.fastq
        ref: Homo_sapiens