outpath:
    /groups/hachgrp/projects/dev-RNAInFuser/analysis/RI-experiments/paper

RI_experiments:
    RI_1:
        sample : 'MCF7-sgnex'
        pipeline:
            - Xpr:
                ''
            - Spc:
                '--molecule-count 1000000'
            - plA:
                '--normal=40,10 --min-length=5 --expand-isoforms'
            - PCR:
                '--cycles 5 -X Taq-setting1'
            - Trc:
                '--only-single-isoform'
            - Seq:
                '--other-br="--tail_noise_model=nanopore"'
    RI_2:
        sample : 'N1'
        pipeline:
            - Xpr_sc:
                ''
            - Spc:
                '--molecule-count 1000000'
            - plA:
                '--normal=40,10 --min-length=5 --expand-isoforms'
            - SCB:
                ''
            - UMI:
                '--format5 10'
            - PCR:
                '--cycles 5 -X Taq-setting1'
            - Trc:
                '--only-single-isoform'
            - Seq:
                '--other-br="--tail_noise_model=nanopore"'
NS_experiments:
    NS_1:
        sample : 'MCF7-sgnex'
        simulation_params:
            '-n 100000 --seed 42'

plots:
    - {
        rule: raw_lengths,
        data: [MCF7-sgnex,NS_1],
        title: ''
    }
    - {
        rule: mapped_raw_lengths,
        data: [MCF7-sgnex, RI_1],
        title: ''
    }
    - {
        rule: mapped_lengths,
        data: [MCF7-sgnex, RI_1],
        title: ''
    }
    - {
        rule: substition,
        data: [MCF7-sgnex, RI_1],
        title: ''
    }
    - {
        rule: polyA,
        data: [MCF7-sgnex, RI_1],
        title: ''
    }

exec:
    RI_splicer:
        build/splicer
    RI_polyA:
        build/polyA
    RI_pcr:
        build/pcr
    RI_sc_barcoder:
        build/single-cell-barcoder
    RI_umi:
        build/umi
    RI_truncate:
        build/truncate
    RI_sequencer:
        build/sequencer
    badread:
        /groups/hachgrp/projects/dev-simulation/code/Badread/badread-runner.py
    transcript_abundance:
        py/transcript_abundance.py
    truncate_kde:
        py/truncate_kde.py
    tNS_simulate:
        read_analysis.py
    tNS_analyze:
        simulator.py

refs:
    cDNA:
        /groups/hachgrp/annotations/cDNA/97/Homo_sapiens.GRCh38.cdna.all.fa
    DNA:
        /groups/hachgrp/annotations/DNA/97/Homo_sapiens.GRCh38.dna.primary_assembly.fa
    GTF:
        /groups/hachgrp/annotations/GTF/97/Homo_sapiens.GRCh38.97.gtf
    10x_bc:
        /groups/hachgrp/software/cellranger/3.0.2/cellranger-cs/3.0.2/lib/python/cellranger/barcodes/3M-february-2018.txt.gz


samples:
    'MCF7-sgnex':
        fastq:
            - /groups/hachgrp/projects/dev-genion/raw-data/wts/fastq/sg-nex-data/SGNex_MCF7_directcDNA_replicate1_run2.fastq.gz
    'N1':
        fastq:
            - /groups/hachgrp/projects/col-flannigan-scrna-2021/raw-data/scrna-long-reads/PAG34747_N1_pass_fastq_concat.fastq
