outpath: /groups/hachgrp/projects/dev-tksm/analysis/paper

TS_experiments:
    TS_1:
        sample: "MCF7-sgnex"
        pipeline:
            - Xpr: ""
            - Spc: "--molecule-count 5000000"
            - plA: "--normal=15,7.5"
            - Trc: ""
            - Seq: "--skip-qual-compute"
    TS_1_chr21:
        sample: "MCF7-sgnex_chr21"
        pipeline:
            - Xpr: ""
            - Spc: "--molecule-count 100000"
            - plA: "--normal=15,7.5"
            - Trc: ""
            - Seq: "--skip-qual-compute"
    TS_2_chr21:
        sample: "N1_chr21"
        pipeline:
            - Xpr_sc: ""
            - Spc: "--molecule-count 100000"
            - plA: "--normal=15,7.5"
            - UMI: "--format5 10 --contig-prefix umi_contig"
            - SCB: ""
            - UMI: "--format5 CTACACGACGCTCTTCCGATCT --contig-prefix sr_adaptor_contig"
            - Trc: ""
            - Seq: "--skip-qual-compute"
    TS_2:
        sample: "N1"
        pipeline:
            - Xpr_sc: ""
            - Spc: "--molecule-count 2500000"
            - plA: "--normal=15,7.5"
            - UMI: "--format5 10 --contig-prefix umi_contig"
            - SCB: ""
            - UMI: "--format5 CTACACGACGCTCTTCCGATCT --contig-prefix sr_adaptor_contig"
            - Trc: ""
            - Seq: "--skip-qual-compute"

NS_experiments:
    NS_1:
        sample: "MCF7-sgnex"
        simulation_params: "-n 1000000 --seed 42"
    NS_1_chr21:
        sample: "MCF7-sgnex_chr21"
        simulation_params: "-n 100000 --seed 42"

plots:
    - {
        rules: [
            # raw_lengths,
            # mapped_raw_lengths,
            mapped_lengths,
            # substitution,
            # polyA,
            tpm_plot_tksm,
            tpm_plot_tksm.by_gene,
            # tpm_plot_tksm_sc.by_gene,
            # tpm_plot_liqa,
            # tpm_plot_nanosim,
            # tpm_plot_minimap2,
            lr_cell_stats,
        ],
        data: [
            N1,
            TS_2,
        ],
      }
    # - {
    #     rules: [
    #         raw_lengths,
    #         mapped_raw_lengths,
    #         mapped_lengths,
    #         substitution,
    #         polyA,
    #         tpm_plot_tksm,
    #         tpm_plot_liqa,
    #         tpm_plot_minimap2,
    #         tpm_plot_nanosim,
    #     ],
    #     data: [
    #         MCF7-sgnex,
    #         NS_1,
    #         TS_1,
    #     ],
    # }

exec:
    tksm: build/bin/tksm
    tNS_analyze: simulator.py

refs:
    Homo_sapiens:
        cDNA: data/refs/Homo_sapiens.GRCh38.cdna.chr.fa
        DNA: data/refs/Homo_sapiens.GRCh38.dna.primary_assembly.fa
        GTF: data/refs/Homo_sapiens.GRCh38.108.chr.gtf
    Homo_sapiens_chr21:
        cDNA: data/refs/Homo_sapiens.GRCh38.cdna.chr21.fa
        DNA: data/refs/Homo_sapiens.GRCh38.dna.primary_assembly.chr21.fa
        GTF: data/refs/Homo_sapiens.GRCh38.108.chr21.gtf
    10x_bc: data/refs/3M-february-2018.txt.gz

samples:
    "MCF7-sgnex":
        fastq:
            - data/samples/MCF7-sgnex.fastq.gz
        ref: Homo_sapiens
    "MCF7-sgnex_chr21":
        fastq:
            - data/samples/MCF7-sgnex_subsample.fastq.gz
        ref: Homo_sapiens_chr21
    "N1":
        fastq:
            - data/samples/N1.fastq
        ref: Homo_sapiens
    "N1_chr21":
        fastq:
            - data/samples/N1_subsample.fastq.gz
        ref: Homo_sapiens_chr21
