outpath: /groups/hachgrp/projects/dev-tksm/analysis/paper

TS_experiments:
    TS_1:
        pipeline:
            - Spc:
                params: "--molecule-count 100000"
                model: "MCF7-sgnex"
                mode: Xpr
            - plA:
                params: "--normal=15,7.5"
            - Flp:
                params: "-p 0.5"
            - Trc:
                params: ""
                model: "MCF7-sgnex"
            - Seq:
                params: "--skip-qual-compute"
                model: "MCF7-sgnex"
    TS_2_head:
        pipeline:
            - Spc:
                params: "--molecule-count 100000"
                model: "N1"
                mode: Xpr_sc
    TS_2_p1:
        pipeline:
            - Mrg:
                sources: ["TS_2_head",]
            - Flt:
                params: "--info CB"
            - Trc:
                params: ""
                model: "N1"
            - plA:
                params: "--normal=15,7.5"
            - Tag: 
                params: "--format3 10 --contig-prefix umi_contig"
            - SCB: 
                params: ""
            - Tag:
                params: "--format3 AGATCGGAAGAGCGTCGTGTAG --contig-prefix sr_adaptor_contig"
    TS_2_p2:
        pipeline:
            - Mrg:
                sources: ["TS_2_head",]
            - Flt:
                params: "--info CB --negate"
    TS_2:
        pipeline:
            - Mrg:
                sources: ["TS_2_p1", "TS_2_p2"]
            - Flp:
                params: "-p 0.5"
            - Tag:
                params: "--format5 AATGTACTTCGTTCAGTTACGTATTGCT --format3 GCAATACGTAACTGAACGAAGT --contig-prefix lr_adaptor_contig"
            - Seq:
                params: "--skip-qual-compute"
                model: "N1"

NS_experiments:
    NS_1:
        sample: "MCF7-sgnex"
        simulation_params: "-n 1000000 --seed 42"
    NS_1_chr21:
        sample: "MCF7-sgnex_chr21"
        simulation_params: "-n 100000 --seed 42"

plots:
    - {
        rules: [
            raw_lengths,
            mapped_raw_lengths,
            mapped_lengths,
            substitution,
            polyA,
            tpm_plot_tksm,
            tpm_plot_tksm.by_gene,
            tpm_plot_tksm_sc.by_gene,
            # tpm_plot_liqa,
            tpm_plot_nanosim,
            tpm_plot_minimap2,
            lr_cell_stats,
        ],
        data: [
            N1_chr,
            TS_2_chr,
        ],
      }
    - {
        rules: [
            raw_lengths,
            mapped_raw_lengths,
            mapped_lengths,
            substitution,
            polyA,
            tpm_plot_tksm,
            # tpm_plot_liqa,
            tpm_plot_minimap2,
            tpm_plot_nanosim,
        ],
        data: [
            MCF7-sgnex,
            NS_1,
            TS_1,
        ],
    }

exec:
    tksm: build/bin/tksm
    tNS_analyze: simulator.py
    lr_cell_stats: py/lr_cell_stats.py

refs:
    Homo_sapiens:
        cDNA: data/refs/Homo_sapiens.GRCh38.cdna.chr.fa
        DNA: data/refs/Homo_sapiens.GRCh38.dna.primary_assembly.fa
        GTF: data/refs/Homo_sapiens.GRCh38.108.chr.gtf
    Homo_sapiens_chr21:
        cDNA: data/refs/Homo_sapiens.GRCh38.cdna.chr21.fa
        DNA: data/refs/Homo_sapiens.GRCh38.dna.primary_assembly.chr21.fa
        GTF: data/refs/Homo_sapiens.GRCh38.108.chr21.gtf
    10x_bc: data/refs/3M-february-2018.txt.gz

samples:
    "MCF7-sgnex":
        fastq:
            - data/samples/MCF7-sgnex.fastq.gz
        ref: Homo_sapiens
    "MCF7-sgnex_chr21":
        fastq:
            - data/samples/MCF7-sgnex_subsample.fastq.gz
        ref: Homo_sapiens_chr21
    "N1":
        fastq:
            - data/samples/N1.fastq
        ref: Homo_sapiens
    "N1_chr21":
        fastq:
            - data/samples/N1_subsample.fastq.gz
        ref: Homo_sapiens_chr21
