outpath: /groups/hachgrp/projects/dev-tksm/analysis/TS-experiments

### Pipeline modules
# Xpr : expression  --> Must be first module only
# Xpr_sc : expression fpr single cells   --> Must be first module only
# Spc : splice --> Must be second module
# Fus : fusion
# PCR : pcr
# plA : polyA
# SCB : single_cell
# Tag : Tag/adapter tag
# Trc : truncate
# Seq : sequence --> Must be last module
TS_experiments:
    small_sc_1:
        sample: "N1_chr21"
        pipeline:
            - Xpr_sc: ""
            - Spc: "--molecule-count 10000"
            - plA: "--normal=40,10 --min-length=5"
            - SCB: ""
            - Tag: "--format5 10"
            - PCR: "--cycles 3 -x Taq-setting1 --molecule-count 10000"
            - Trc: ""
            - Seq: "--skip-qual-compute"

exec:
    tksm: build/bin/tksm

refs:
    Homo_sapiens:
        cDNA: data/refs/Homo_sapiens.GRCh38.cdna.chr.fa
        DNA: data/refs/Homo_sapiens.GRCh38.dna.primary_assembly.fa
        GTF: data/refs/Homo_sapiens.GRCh38.108.chr.gtf
    Homo_sapiens_chr21:
        cDNA: data/refs/Homo_sapiens.GRCh38.cdna.chr21.fa
        DNA: data/refs/Homo_sapiens.GRCh38.dna.primary_assembly.chr21.fa
        GTF: data/refs/Homo_sapiens.GRCh38.108.chr21.gtf
    10x_bc: data/refs/3M-february-2018.txt.gz

samples:
    "MCF7-sgnex":
        fastq:
            - data/samples/MCF7-sgnex.fastq.gz
        ref: Homo_sapiens
    "MCF7-sgnex_chr21":
        fastq:
            - data/samples/MCF7-sgnex_subsample.fastq.gz
        ref: Homo_sapiens_chr21
    "N1":
        fastq:
            - data/samples/N1.fastq
        ref: Homo_sapiens
    "N1_chr21":
        fastq:
            - data/samples/N1_subsample.fastq.gz
        ref: Homo_sapiens_chr21
