outpath: /groups/hachgrp/projects/dev-tksm/analysis/TS-experiments

# Pipeline modules

# Entry point for the pipeline
## Mrg :
### Merge the output of multiple pipelines into a single MDF and use it as input.
### Takes sources key-value pair whose value is a list of pipeline names to merge.
### The multiple pipelines can have different models and different references.
### Must include params key-value as a list (not string) of pipeline names to merge.
## Spc : 
### Splice the genome. Generates transcripts based on the model expression.
### Must include mode (either Xpr or Xpr_sc) and model (sample name) key-value pairs.
### Allows for params key-value pair

# Modules with MDF as input and MDF as output. All these modules take params key-value pair
# Flt : Filters molecules out molecules that fail the given conditions
# PCR : PCR amplification
# plA : polyA tailing
# SCB : Single-cell barcoding of molecules (from tags added by Spc module with Xpr_sc mode)
# Tag : Tag the molecules with on 5' or 3' end with specified FASTA pattern
# Flp : Flib the molecule strands with a given probability
# Trc : Truncate the molecules. Takes model (sample name) key-value pair

# Model with FASTQ/A as output
# Seq : 
### Sequence the molecules. Can only be last module. 
### Takes model (sample name or TKSM error/qscore model name) key-value pair.
TS_experiments:
    P1:
        pipeline:
            - Spc:
                params: "--molecule-count 10000"
                model: "MCF7-sgnex_chr21"
                mode: Xpr
    P2:
        pipeline:
            - Spc:
                params: "--molecule-count 10000"
                model: "N1_chr21"
                mode: Xpr_sc
    E1:
        pipeline:
            - Mrg:
                sources: ["P1", "P2"]
            - Flt:
                params: "--c1 c1"
            - SCB:
                params: ""
            - Tag:
                params: "--format5 10"
            - PCR:
                params: "--cycles 3 -x Taq-setting1 --molecule-count 10000"
            - Trc:
                params: ""
                model: "N1_chr21"
            - Seq:
                params: "--skip-qual-compute"
                model: "N1"

exec:
    tksm: build/bin/tksm

refs:
    Homo_sapiens:
        cDNA: data/refs/Homo_sapiens.GRCh38.cdna.chr.fa
        DNA: data/refs/Homo_sapiens.GRCh38.dna.primary_assembly.fa
        GTF: data/refs/Homo_sapiens.GRCh38.108.chr.gtf
    Homo_sapiens_chr21:
        cDNA: data/refs/Homo_sapiens.GRCh38.cdna.chr21.fa
        DNA: data/refs/Homo_sapiens.GRCh38.dna.primary_assembly.chr21.fa
        GTF: data/refs/Homo_sapiens.GRCh38.108.chr21.gtf
    10x_bc: data/refs/3M-february-2018.txt.gz

samples:
    "MCF7-sgnex":
        fastq:
            - data/samples/MCF7-sgnex.fastq.gz
        ref: Homo_sapiens
    "MCF7-sgnex_chr21":
        fastq:
            - data/samples/MCF7-sgnex_subsample.fastq.gz
        ref: Homo_sapiens_chr21
    "N1":
        fastq:
            - data/samples/N1.fastq
        ref: Homo_sapiens
    "N1_chr21":
        fastq:
            - data/samples/N1_subsample.fastq.gz
        ref: Homo_sapiens_chr21
