outpath:
    /groups/hachgrp/projects/dev-RNAInFuser/analysis/RI-experiments

### Pipeline modules
# Xpr : expression  --> Must be first module only
# Xpr_sc : expression fpr single cells   --> Must be first module only
# Spc : splice --> Must be second module
# Fus : fusion
# PCR : pcr
# plA : polyA
# UMI : umi
# SCB : single_cell
# Trc : truncate
# Seq : sequence --> Must be last module
experiments:
    e1:
        sample : "N1"
        pipeline:
            - Xpr_sc:
                ''
            - Spc:
                '--molecule-count 1000000'
            - plA:
                '--normal=40,10 --min-length=5 --expand-isoforms'
            - PCR:
                '--cycles 5 -X Taq-setting1'
            - Trc:
                '--only-single-isoform'
            - Seq:
                '--other-br="--tail_noise_model=nanopore"'

exec:
    transcript_abundance:
        /groups/hachgrp/projects/dev-RNAInFuser/scripts/RNAInFuser/py/transcript_abundance.py
    RI_splicer:
        /groups/hachgrp/projects/dev-RNAInFuser/scripts/RNAInFuser/build/splicer
    RI_polyA:
        /groups/hachgrp/projects/dev-RNAInFuser/scripts/RNAInFuser/build/polyA
    RI_truncate:
        /groups/hachgrp/projects/dev-RNAInFuser/scripts/RNAInFuser/build/truncate
    RI_truncate_kde:
        grid:
            /groups/hachgrp/projects/dev-genion/code/kernels/p.npy
        labels:
            /groups/hachgrp/projects/dev-genion/code/kernels/grid.npy
    RI_sequencer:
        /groups/hachgrp/projects/dev-RNAInFuser/scripts/RNAInFuser/build/sequencer
    RI_pcr:
        /groups/hachgrp/projects/dev-RNAInFuser/scripts/RNAInFuser/build/pcr
    badread:
        /groups/hachgrp/projects/dev-simulation/code/Badread/badread-runner.py
    scTagger:
        /groups/hachgrp/projects/dev-RNAInFuser/scripts/scTagger/scTagger.py

refs:
    cDNA:
        /groups/hachgrp/annotations/cDNA/97/Homo_sapiens.GRCh38.cdna.all.fa
    DNA:
        /groups/hachgrp/annotations/DNA/97/Homo_sapiens.GRCh38.dna.primary_assembly.fa
    GTF:
        /groups/hachgrp/annotations/GTF/97/Homo_sapiens.GRCh38.97.gtf
    10x_bc:
        /groups/hachgrp/software/cellranger/3.0.2/cellranger-cs/3.0.2/lib/python/cellranger/barcodes/3M-february-2018.txt.gz


samples:
    "MCF7-sgnex":
        fastq:
            - /groups/hachgrp/projects/dev-genion/raw-data/wts/fastq/sg-nex-data/SGNex_MCF7_directcDNA_replicate1_run2.fastq.gz
    "N1":
        fastq:
            - /groups/hachgrp/projects/col-flannigan-scrna-2021/raw-data/scrna-long-reads/PAG34747_N1_pass_fastq_concat.fastq
