name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  mambaforge:
      name: Ex10 (${{ matrix.os }}, Mambaforge)
      runs-on: ${{ matrix.os }}-latest
      defaults:
        run:
          shell: bash -l {0}
      strategy:
        fail-fast: false
        matrix:
          os: ["ubuntu"]
          include:
            - os: ubuntu
              environment-file: env-dev.yaml
              miniforge-variant: Mambaforge
              miniforge-version: 4.9.2-4
              prefix: /usr/share/miniconda3/envs/tksm
      steps:
          - uses: actions/checkout@v2
          - name: create env with miniforge
            uses: conda-incubator/setup-miniconda@v2
            with:
              condarc-file: ${{ matrix.condarc-file }}
              miniforge-variant: ${{ matrix.miniforge-variant }}
              miniforge-version: ${{ matrix.miniforge-version }}
              auto-activate-base: false
              activate-environment: tksm
              use-mamba: true
              
          - name: Set cache date
            run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
            
          - uses: actions/cache@v2
            with:
              path: ${{ matrix.prefix }}
              key: ${{ matrix.label }}-conda-${{ hashFiles( '${{ matrix.environment-file }}') }}-${{ env.DATE }}-${{ env.CACHE_NUMBER }}
            id: cache
          - name: Update environment
            run: mamba env update -n my-env -f ${{ matrix.environment-file }}
            if: steps.cache.outputs.cache-hit != 'true'
          - name: check solution
            run: |
              mamba env export
          - name: make
            run: make
          - name: make check
            run: make check

