name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  mambaforge:
      name: Ex10 (${{ matrix.os }}, Mambaforge)
      runs-on: ${{ matrix.os }}-latest
      strategy:
        fail-fast: false
        matrix:
          os: ["ubuntu"]
          include:
            - os: ubuntu
              environment-file: env-dev.yaml
              miniforge-variant: Mambaforge
              miniforge-version: 4.9.2-4
      steps:
          - uses: actions/checkout@v2
          - name: create env with miniforge
            uses: conda-incubator/setup-miniconda@v2
            with:
              condarc-file: ${{ matrix.condarc-file }}
              environment-file: ${{ matrix.environment-file }}
              miniforge-variant: ${{ matrix.miniforge-variant }}
              miniforge-version: ${{ matrix.miniforge-version }}
              auto-activate-base: false
              activate-environment: tksm
              use-mamba: true
          - name: check solution
            run: |
              mamba env export
          - name: make
            run: make
          - name: make check
            run: make check

